import {
  Bath,
  BedDouble,
  Bike,
  Building2,
  Castle,
  Coffee,
  Compass,
  Cross,
  Droplets,
  Gamepad2,
  Grape,
  HeartPulse,
  Hospital,
  Leaf,
  PawPrint,
  ShieldCheck,
  ShipWheel,
  ShoppingBag,
  Soup,
  Store,
  TreePine,
  Trees,
  Users,
  Utensils,
  Wine,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  bath: Bath,
  bed: BedDouble,
  bike: Bike,
  building: Building2,
  castle: Castle,
  coffee: Coffee,
  compass: Compass,
  cross: Cross,
  droplets: Droplets,
  gamepad: Gamepad2,
  grape: Grape,
  heart: HeartPulse,
  hospital: Hospital,
  leaf: Leaf,
  paw: PawPrint,
  shield: ShieldCheck,
  ship: ShipWheel,
  shopping: ShoppingBag,
  soup: Soup,
  store: Store,
  tree: TreePine,
  trees: Trees,
  users: Users,
  utensils: Utensils,
  wine: Wine,
};

export function contentIcon(name: string, fallback: LucideIcon = Compass) {
  return icons[name] ?? fallback;
}
